#ifndef IMAGINEBOTS_V2_CONSTANTS_H
#define IMAGINEBOTS_V2_CONSTANTS_H

#define SHOOTBOT_PICKUP_LOW 0
#define SHOOTBOT_PICKUP_HIGH 140

#define  ARMBOT_ARM_LOW 0
#define  ARMBOT_ARM_HIGH 65

#define  ARMBOT_CLAW_CLOSED 0
#define  ARMBOT_CLAW_OPEN 30

#define FIELD_ADDRESS_RF24 "FLD"

#define REMOTE_ADDRESS_1_RF24 "R01"
#define REMOTE_ADDRESS_2_RF24 "R02"
#define REMOTE_ADDRESS_2_RF24 "R03"
#define REMOTE_ADDRESS_3_RF24 "R04"

#define ROBOT_ADDRESS_1_RF24 "B01"
#define ROBOT_ADDRESS_2_RF24 "B02"
#define ROBOT_ADDRESS_3_RF24 "B03"
#define ROBOT_ADDRESS_4_RF24 "B04"

#define FIELD_ADDRESS_Rh 0XFD

#define REMOTE_ADDRESS_1_RH 0XE1
#define REMOTE_ADDRESS_2_RH 0XE2
#define REMOTE_ADDRESS_3_RH 0XE3
#define REMOTE_ADDRESS_4_RH 0XE4

#define REMOTE_ADDRESS_1_RH 0XB1
#define REMOTE_ADDRESS_2_RH 0XB2
#define REMOTE_ADDRESS_3_RH 0XB3
#define REMOTE_ADDRESS_4_RH 0XB4

#define LED_MAGENTA_R 254
#define LED_MAGENTA_G 50
#define LED_MAGENTA_B 254

#define LED_CYAN_R 50
#define LED_CYAN_G 254
#define LED_CYAN_B 254

#define LED_YELLOW_R 254
#define LED_YELLOW_G 254
#define LED_YELLOW_B 50

#define LED_GREEN_R 50
#define LED_GREEN_G 254
#define LED_GREEN_B 50
#endif